[package]
name = "aster-sql"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Hand-written SQL parser, binder, and optimizer for AsterDB"

[dependencies]
aster-core = { path = "../aster-core", version = "0.1.0" }

[lints]
workspace = true
